//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YUTPLAT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class YUTPLAT_DESAEntities : DbContext
    {
        public YUTPLAT_DESAEntities()
            : base("name=YUTPLAT_DESAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int ObtenerMedicionPorMes(Nullable<int> mes)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ObtenerMedicionPorMes", mesParameter);
        }
    
        public virtual ObjectResult<ObtenerTodasMediciones_Result> ObtenerTodasMediciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerTodasMediciones_Result>("ObtenerTodasMediciones");
        }
    }
}
