// <auto-generated />
namespace YUTPLAT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Creacion_Inicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creacion_Inicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201710050326098_Creacion_Inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
