// <auto-generated />
namespace YUTPLAT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SeagregaEsAutomaticoenindicador : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeagregaEsAutomaticoenindicador));
        
        string IMigrationMetadata.Id
        {
            get { return "201803020101112_Se agrega EsAutomatico en indicador"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
