
CREATE TABLE TEMP_INDICADORES (

	ID int IDENTITY(1,1) PRIMARY KEY,
	
	IND_NOMBRE NVARCHAR(MAX),	
	IND_OBJETIVO NVARCHAR(MAX),		
	IND_FRECUENCIA_MEDICION NVARCHAR(MAX),	
	IND_DESCRIPCION NVARCHAR(MAX),	
		
	MET_INACEPTABLE_VALOR1 DECIMAL(18,3),
	MET_INACEPTABLE_SIGNO1 INT,
	MET_INACEPTABLE_SIGNO2 INT,
	MET_INACEPTABLE_VALOR2 DECIMAL(18,3),
			
	MET_A_MEJORAR_VALOR1 DECIMAL(18,3),
	MET_A_MEJORAR_SIGNO1 INT,
	MET_A_MEJORAR_SIGNO2 INT,
	MET_A_MEJORAR_VALOR2 DECIMAL(18,3),
		
	MET_ACEPTABLE_VALOR1 DECIMAL(18,3),
	MET_ACEPTABLE_SIGNO1 INT,
	MET_ACEPTABLE_SIGNO2 INT,
	MET_ACEPTABLE_VALOR2 DECIMAL(18,3),
	
	MET_SATISFACTORIA_VALOR1 DECIMAL(18,3),
	MET_SATISFACTORIA_SIGNO1 INT,
	MET_SATISFACTORIA_SIGNO2 INT,
	MET_SATISFACTORIA_VALOR2 DECIMAL(18,3),
		
	MET_EXCELENTE_VALOR1 DECIMAL(18,3),
	MET_EXCELENTE_SIGNO1 INT,
	MET_EXCELENTE_SIGNO2 INT,
	MET_EXCELENTE_VALOR2 DECIMAL(18,3),
	
	RES_USERNAME1 NVARCHAR(256),
	RES_USERNAME2 NVARCHAR(256)
);