
INSERT INTO dbo.Indicador (Nombre, Descripcion, FechaCreacion, ObjetivoID, FrecuenciaMedicionIndicadorID, Grupo, ID_TEMP)
SELECT 
	TI.IND_NOMBRE, TI.IND_DESCRIPCION, GETDATE(), OB.Id, FMI.FrecuenciaMedicionIndicadorID, 1, TI.ID
FROM 
	dbo.TEMP_INDICADORES TI
	INNER JOIN dbo.Objetivo OB on OB.Nombre = TI.IND_OBJETIVO
	INNER JOIN dbo.FrecuenciaMedicionIndicador FMI ON FMI.Descripcion = TI.IND_FRECUENCIA_MEDICION

	
UPDATE dbo.Indicador SET Grupo = IndicadorID
	
	
INSERT INTO dbo.Meta (Valor1, Valor2, Signo1, Signo2, ID_TEMP, TEMP_TIPO) 
SELECT 
	TI.MET_INACEPTABLE_VALOR1, TI.MET_INACEPTABLE_VALOR2, TI.MET_INACEPTABLE_SIGNO1, TI.MET_INACEPTABLE_SIGNO2, TI.ID, 1
FROM
	dbo.TEMP_INDICADORES TI

INSERT INTO dbo.Meta (Valor1, Valor2, Signo1, Signo2, ID_TEMP, TEMP_TIPO) 
SELECT 
	TI.MET_A_MEJORAR_VALOR1, TI.MET_A_MEJORAR_VALOR2, TI.MET_A_MEJORAR_SIGNO1, TI.MET_A_MEJORAR_SIGNO2, TI.ID, 2
FROM
	dbo.TEMP_INDICADORES TI
	
INSERT INTO dbo.Meta (Valor1, Valor2, Signo1, Signo2, ID_TEMP, TEMP_TIPO) 
SELECT 
	TI.MET_ACEPTABLE_VALOR1, TI.MET_ACEPTABLE_VALOR2, TI.MET_ACEPTABLE_SIGNO1, TI.MET_ACEPTABLE_SIGNO2, TI.ID, 3
FROM
	dbo.TEMP_INDICADORES TI
	
INSERT INTO dbo.Meta (Valor1, Valor2, Signo1, Signo2, ID_TEMP, TEMP_TIPO) 
SELECT 
	TI.MET_SATISFACTORIA_VALOR1, TI.MET_SATISFACTORIA_VALOR2, TI.MET_SATISFACTORIA_SIGNO1, TI.MET_SATISFACTORIA_SIGNO2, TI.ID, 4
FROM
	dbo.TEMP_INDICADORES TI
	
INSERT INTO dbo.Meta (Valor1, Valor2, Signo1, Signo2, ID_TEMP, TEMP_TIPO) 
SELECT 
	TI.MET_EXCELENTE_VALOR1, TI.MET_EXCELENTE_VALOR2, TI.MET_EXCELENTE_SIGNO1, TI.MET_EXCELENTE_SIGNO2, TI.ID, 5
FROM
	dbo.TEMP_INDICADORES TI
	
UPDATE 
	IND 
SET 
	IND.MetaInaceptableMetaID = ME.MetaId
FROM 
	dbo.Indicador IND 	
	INNER JOIN dbo.Meta ME ON ME.ID_TEMP = IND.ID_TEMP
WHERE 
	ME.TEMP_TIPO = 1

	UPDATE 
	IND 
SET 
	IND.MetaAMejorarMetaID = ME.MetaId
FROM 
	dbo.Indicador IND 	
	INNER JOIN dbo.Meta ME ON ME.ID_TEMP = IND.ID_TEMP
WHERE 
	ME.TEMP_TIPO = 2
	
UPDATE 
	IND 
SET 
	IND.MetaAceptableMetaID = ME.MetaId
FROM 
	dbo.Indicador IND 	
	INNER JOIN dbo.Meta ME ON ME.ID_TEMP = IND.ID_TEMP
WHERE 
	ME.TEMP_TIPO = 3
	
UPDATE 
	IND 
SET 
	IND.MetaSatisfactoriaMetaID = ME.MetaId
FROM 
	dbo.Indicador IND 	
	INNER JOIN dbo.Meta ME ON ME.ID_TEMP = IND.ID_TEMP
WHERE 
	ME.TEMP_TIPO = 4
	
UPDATE 
	IND 
SET 
	IND.MetaExcelenteMetaID = ME.MetaId
FROM 
	dbo.Indicador IND 	
	INNER JOIN dbo.Meta ME ON ME.ID_TEMP = IND.ID_TEMP
WHERE 
	ME.TEMP_TIPO = 5
